/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: 'span';
        _key: string;
      }>;
      style?: 'normal' | 'h2' | 'h3' | 'blockquote';
      listItem?: 'bullet' | 'number';
      markDefs?: Array<{
        href?: string;
        _type: 'link';
        _key: string;
      }>;
      level?: number;
      _type: 'block';
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      caption?: string;
      _type: 'contentImage';
      _key: string;
    }
>;

export type FerryRoute = {
  _id: string;
  _type: 'ferryRoute';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  routeName?: string;
  slug?: Slug;
  operator?: string;
  departurePort?: string;
  arrivalPort?: string;
  crossingDurationHours?: number;
  schedule?: Array<{
    weekday?: 'ma' | 'ti' | 'ke' | 'to' | 'pe' | 'la' | 'su';
    departureTime?: string;
    arrivalTime?: string;
    _type: 'departure';
    _key: string;
  }>;
  vehiclePricing?: Array<{
    vehicleType?: 'motorcycle' | 'car' | 'van' | 'van_trailer';
    direction?: 'meno' | 'paluu' | 'molemmat';
    priceEur?: number;
    includesCabin?: boolean;
    notes?: string;
    _type: 'vehiclePrice';
    _key: string;
  }>;
  validFrom?: string;
  validUntil?: string;
  usedByFinishpoint?: boolean;
  usedByMpLogistiikka?: boolean;
};

export type Slug = {
  _type: 'slug';
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: 'category';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type AuthorReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'author';
};

export type CategoryReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'category';
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  publishedAt?: string;
  author?: AuthorReference;
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  body?: BlockContent;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Author = {
  _id: string;
  _type: 'author';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  image?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  bio?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: 'span';
      _key: string;
    }>;
    style?: 'normal';
    listItem?: 'bullet' | 'number';
    markDefs?: Array<{
      href?: string;
      _type: 'link';
      _key: string;
    }>;
    level?: number;
    _type: 'block';
    _key: string;
  }>;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | BlockContent
  | FerryRoute
  | Slug
  | Category
  | AuthorReference
  | CategoryReference
  | Post
  | SanityImageCrop
  | SanityImageHotspot
  | Author
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: ../mp-logistiikka/sanity/lib/queries.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && defined(slug.current)]  | order(publishedAt desc) {      _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage,  "author": author->{_id, name},  "categories": categories[]->{_id, title, "slug": slug.current}  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  author: {
    _id: string;
    name: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
}>;

// Source: ../mp-logistiikka/sanity/lib/queries.ts
// Variable: POST_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{      _id,  title,  "slug": slug.current,  excerpt,  publishedAt,  mainImage,  "author": author->{_id, name},  "categories": categories[]->{_id, title, "slug": slug.current},    body[]{      ...,      _type == "block" => { markDefs[]{ ..., _type == "link" => { href } } },      _type == "contentImage" => { asset, hotspot, crop, alt, caption }    }  }
export type POST_QUERY_RESULT = {
  _id: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  author: {
    _id: string;
    name: string | null;
  } | null;
  categories: Array<{
    _id: string;
    title: string | null;
    slug: string | null;
  }> | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h2' | 'h3' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs: Array<{
          href: string | null;
          _type: 'link';
          _key: string;
        }> | null;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset: SanityImageAssetReference | null;
        media?: unknown;
        hotspot: SanityImageHotspot | null;
        crop: SanityImageCrop | null;
        alt: string | null;
        caption: string | null;
        _type: 'contentImage';
        _key: string;
      }
  > | null;
} | null;

// Source: ../mp-logistiikka/sanity/lib/queries.ts
// Variable: POST_SEO_QUERY
// Query: *[_type == "post" && slug.current == $slug][0]{    title,    excerpt,    publishedAt,    mainImage  }
export type POST_SEO_QUERY_RESULT = {
  title: string | null;
  excerpt: string | null;
  publishedAt: string | null;
  mainImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
} | null;

// Source: ../mp-logistiikka/sanity/lib/queries.ts
// Variable: POST_SLUGS_QUERY
// Query: *[_type == "post" && defined(slug.current)]{ "slug": slug.current }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string | null;
}>;

// Source: ../mp-logistiikka/sanity/lib/queries.ts
// Variable: MP_FERRY_ROUTES_QUERY
// Query: *[_type == "ferryRoute" && usedByMpLogistiikka == true]  | order(routeName asc) {    _id,    routeName,    operator,    crossingDurationHours,    vehiclePricing[]{      _key,      vehicleType,      direction,      priceEur,      includesCabin,      notes    }  }
export type MP_FERRY_ROUTES_QUERY_RESULT = Array<{
  _id: string;
  routeName: string | null;
  operator: string | null;
  crossingDurationHours: number | null;
  vehiclePricing: Array<{
    _key: string;
    vehicleType: 'car' | 'motorcycle' | 'van_trailer' | 'van' | null;
    direction: 'meno' | 'molemmat' | 'paluu' | null;
    priceEur: number | null;
    includesCabin: boolean | null;
    notes: string | null;
  }> | null;
}>;

// Source: ../mp-logistiikka/sanity/lib/queries.ts
// Variable: POSTS_SITEMAP_QUERY
// Query: *[_type == "post" && defined(slug.current)]  | order(publishedAt desc) {    "slug": slug.current,    _updatedAt  }
export type POSTS_SITEMAP_QUERY_RESULT = Array<{
  slug: string | null;
  _updatedAt: string;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "post" && defined(slug.current)]\n  | order(publishedAt desc) {\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage,\n  "author": author->{_id, name},\n  "categories": categories[]->{_id, title, "slug": slug.current}\n\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    \n  _id,\n  title,\n  "slug": slug.current,\n  excerpt,\n  publishedAt,\n  mainImage,\n  "author": author->{_id, name},\n  "categories": categories[]->{_id, title, "slug": slug.current}\n,\n    body[]{\n      ...,\n      _type == "block" => { markDefs[]{ ..., _type == "link" => { href } } },\n      _type == "contentImage" => { asset, hotspot, crop, alt, caption }\n    }\n  }\n': POST_QUERY_RESULT;
    '\n  *[_type == "post" && slug.current == $slug][0]{\n    title,\n    excerpt,\n    publishedAt,\n    mainImage\n  }\n': POST_SEO_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]{ "slug": slug.current }\n': POST_SLUGS_QUERY_RESULT;
    '\n  *[_type == "ferryRoute" && usedByMpLogistiikka == true]\n  | order(routeName asc) {\n    _id,\n    routeName,\n    operator,\n    crossingDurationHours,\n    vehiclePricing[]{\n      _key,\n      vehicleType,\n      direction,\n      priceEur,\n      includesCabin,\n      notes\n    }\n  }\n': MP_FERRY_ROUTES_QUERY_RESULT;
    '\n  *[_type == "post" && defined(slug.current)]\n  | order(publishedAt desc) {\n    "slug": slug.current,\n    _updatedAt\n  }\n': POSTS_SITEMAP_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
